### ISSUE TITLE
Check Images and Links in specification documents

### ISSUE THREAD

**Issue by tsurdilo** [cncf/wg-serverless-workflow#13]
**Why is this needed**:
We recently moved to this repository and did a little restructuring of documents and their locations.

It would be great if we can please check all the images and links in spec documents to make sure they are still valid and work.

Thanks!

**Comment by manuelstein** [comment]
Links checked using https://github.com/tcort/markdown-link-check

**Comment by tsurdilo** [comment]
@manuelstein yeah i added that after opening this issue :) feel free to close this one if you wish.

**Comment by manuelstein** [comment]
I haven't checked images. The tool I used doesn't do embedded HTML, so I was thinking of using markdown style images. Since that wouldn't allow scaling (heights in use cases), I was thinking of resizing images, so we can have pure markdown. wdyt?
