### ISSUE TITLE
Create a workflow to publish Java SDK snapshots into Maven Central

### ISSUE THREAD

**Issue by ricardozanini** [cncf/wg-serverless-workflow#59]
Would be nice to push new SNAPSHOTS into Maven Central, so community members could try the SDK with the latest updates.

A Github workflow can run every time we push modifications on `sdk/java` to `master` branch.

This one can be used: https://github.com/marketplace/actions/maven-release-fork

**Comment by tsurdilo** [comment]
+1

**Comment by tsurdilo** [comment]
actiion to publish added
